/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Doctor;

import Business.Business;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabWorkRequest;
import java.awt.CardLayout;
import java.util.Properties;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dalea
 */
public class WorkRequestDocPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkRequestDocPanel
     */
    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;
    LabWorkRequest workRequest;
    LabWorkRequest labTestWorkRequest;
    public WorkRequestDocPanel(JPanel userProcessContainer, Business business, UserAccount account, LabWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = account;
        this.workRequest = workRequest;
        changeButtonText();
        display();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void display() {
        customerNameValue.setText(workRequest.getPatient().getName());
        status.setText(workRequest.getStatus());
        heartrate.setText(workRequest.getPatient().getHeartRate());
        oxygenlevel.setText(workRequest.getPatient().getOxygenlevel());
        bloodpressure.setText(workRequest.getPatient().getBloodPressure());

    }
    
    private void changeButtonText() {
        switch (workRequest.getStatus()) {
            case "Doctor Assigned":
                btnStatus.setText("Schedule Appointment");
                break;
            case "Zoom meeting scheduled":
                btnStatus.setText("Complete Appointment");
                break;
            default:
                btnStatus.setVisible(false);
                break;
        }
    }
     private static void sendFromGMail(String from, String pass, String[] to, String subject, String body) {
        Properties props = System.getProperties();
        String host = "smtp.gmail.com";
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.user", from);
        props.put("mail.smtp.password", pass);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");

        Session session = Session.getDefaultInstance(props);
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(from));
            InternetAddress[] toAddress = new InternetAddress[to.length];

            // To get the array of addresses
            for( int i = 0; i < to.length; i++ ) {
                toAddress[i] = new InternetAddress(to[i]);
            }

            for( int i = 0; i < toAddress.length; i++) {
                message.addRecipient(Message.RecipientType.TO, toAddress[i]);
            }

            message.setSubject(subject);
            message.setText(body);
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
        }
        catch (AddressException ae) {
            ae.printStackTrace();
        }
        catch (MessagingException me) {
            me.printStackTrace();
        }
    }
    
    private void sendMail(){
        String from = "newlifecentersystem@gmail.com";
        String pass = "trjhduhplnrblqco";
        String[] to = { workRequest.getPatient().getEmail() }; // list of recipient email addresses
        String subject = "ZOOM LINK";
        String body = zoomLinkTxtField.getText();

        sendFromGMail(from, pass, to, subject, body);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        customerNameValue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnStatus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        zoomLinkTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        heartrate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bloodpressure = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oxygenlevel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(163, 186, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 105, 137));
        backJButton.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Patient Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 151, -1, -1));

        customerNameValue.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        customerNameValue.setText("<Value>");
        jPanel1.add(customerNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 151, 258, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 51, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("APPOINTMENT DETAILS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 889, -1));

        btnStatus.setBackground(new java.awt.Color(0, 105, 137));
        btnStatus.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnStatus.setText("Schedule Appointment");
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        jPanel1.add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 235, 45));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 193, -1, -1));

        status.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        status.setText("<Value>");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 190, 258, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Zoom Link");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 351, -1, -1));

        zoomLinkTxtField.setEditable(false);
        zoomLinkTxtField.setBackground(new java.awt.Color(203, 213, 220));
        zoomLinkTxtField.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        zoomLinkTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        zoomLinkTxtField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        zoomLinkTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomLinkTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(zoomLinkTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 349, 306, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 469, 859, 330));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setText("Patient Heart Rate");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 232, -1, -1));

        heartrate.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        heartrate.setText("<Value>");
        jPanel1.add(heartrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 232, 258, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setText("Patient Blood Pressure");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 271, -1, -1));

        bloodpressure.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        bloodpressure.setText("<Value>");
        jPanel1.add(bloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 271, 258, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setText("Patient Oxygen Level");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 310, -1, -1));

        oxygenlevel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        oxygenlevel.setText("<Value>");
        jPanel1.add(oxygenlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 310, 258, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        DoctorAreaPanel doctorAreaJPanel = new DoctorAreaPanel(userProcessContainer, userAccount, business);
        userProcessContainer.add("doctorAreaJPanel", doctorAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void zoomLinkTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomLinkTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomLinkTxtFieldActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
        System.out.println(workRequest.getStatus());
        if (workRequest.getStatus().equals("Doctor Assigned")) {
            System.out.println("inside if");
            ThreadLocalRandom random = ThreadLocalRandom.current();
            int leftLimit = 48; // numeral '0'
            int rightLimit = 122; // letter 'z'
            int targetStringLength = 31;
            Random r = new Random();
            String generatedString = r.ints(leftLimit, rightLimit + 1).filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97)).limit(targetStringLength).collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append).toString();
            String url = "https://zoom.us/j/"+random.nextLong(10_000_000_000L, 100_000_000_000L)+"?pwd="+generatedString;
            System.out.println(url);
            zoomLinkTxtField.setText(url);
            workRequest.setZoomLink(zoomLinkTxtField.getText());
            sendMail();
            workRequest.setStatus("Zoom meeting scheduled");
            workRequest.setTestResult("Meeting in Process");
            JOptionPane.showMessageDialog(null, "Meeting will start");
            zoomLinkTxtField.setEnabled(false);
        } else if (workRequest.getStatus().equals("Zoom meeting scheduled")) {
            System.out.println("inside elif");
            workRequest.setStatus("Meeting ended");
            workRequest.setTestResult("Meeting Completed");
            JOptionPane.showMessageDialog(null, "Meeting has ended");
        } else {
            System.out.println("inside else");
            btnStatus.setVisible(false);
        }
        changeButtonText();
        status.setText(workRequest.getStatus());
    }//GEN-LAST:event_btnStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel bloodpressure;
    private javax.swing.JButton btnStatus;
    private javax.swing.JLabel customerNameValue;
    private javax.swing.JLabel heartrate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel oxygenlevel;
    private javax.swing.JLabel status;
    private javax.swing.JTextField zoomLinkTxtField;
    // End of variables declaration//GEN-END:variables
}
