/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Nurse;

import Business.Business;
import Business.Doctors.Doctor;
import Business.Doctors.DoctorDirectory;
import Business.Porter.PorterDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prach
 */
public class AcceptOrRejectOrder extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount userAccount;
    Business business;
    LabWorkRequest labTestWorkRequest;
    double total = 0.0;
    private PorterDirectory deliveryManDirectory;
    private DoctorDirectory doctorDirectory;
    private int index = -1;

    /**
     * Creates new form AcceptOrRejectOrder
     */
    public AcceptOrRejectOrder(JPanel userProcessContainer, Business business, UserAccount userAccount, LabWorkRequest labTestWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        this.labTestWorkRequest = labTestWorkRequest;
        deliveryManDirectory = business.getDeliveryManDirectory();
        doctorDirectory = business.getDoctorDirectory();
        fillDelList(doctorDirectory.getDoctorList());
        change();
        display();
    }

    private void display() {

        fillDelUI();

        status.setText(labTestWorkRequest.getStatus());
        message.setText(labTestWorkRequest.getMessage());

    }

    private void declineOrder() {
        labTestWorkRequest.setStatus("Declined");
        JOptionPane.showMessageDialog(null, "Appointment has been declined");
        change();
        status.setText(labTestWorkRequest.getStatus());
    }

    private void change() {
        switch (labTestWorkRequest.getStatus()) {
            case "Request to Hospital": {
                acceptOrder.setText("Accept appointment");
                declineOrder.setVisible(true);
                break;
            }
            case "Waiting for doctor to be assigned": {
                acceptOrder.setText("Ping the Doctor");
                declineOrder.setVisible(false);
                break;
            }
            default: {
                declineOrder.setVisible(false);
                acceptOrder.setVisible(false);
                break;
            }
        }
        fillDelUI();
    }

    private void fillDelUI() {
        if (labTestWorkRequest.getDoctor() == null && !("ordered".equalsIgnoreCase(labTestWorkRequest.getStatus()) || "declined".equalsIgnoreCase(labTestWorkRequest.getStatus()))) {
            assignDeliveryPersonLabel.setVisible(true);
            assignDeliveryPerson.setVisible(true);

            jButtonAddDeliveryMan.setVisible(true);

        } else {
            jButtonAddDeliveryMan.setVisible(false);
            assignDeliveryPersonLabel.setVisible(false);
            assignDeliveryPerson.setVisible(false);

        }
    }

    public void fillDelList(ArrayList<Doctor> doctorList) {
        if (labTestWorkRequest.getDeliverMan() == null) {
            assignDeliveryPerson.setVisible(true);
            for (Doctor doctor : doctorList) {
                assignDeliveryPerson.addItem(doctor.getName());
            }
        } else {
            assignDeliveryPerson.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        acceptOrder = new javax.swing.JButton();
        assignDeliveryPerson = new javax.swing.JComboBox<>();
        jButtonAddDeliveryMan = new javax.swing.JButton();
        assignDeliveryPersonLabel = new javax.swing.JLabel();
        declineOrder = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(163, 186, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel10.setText("Message");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 110, -1));

        message.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        message.setText("<value>");
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 330, -1));

        jLabel12.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("APPOINTMENT DETAILS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 21, 990, 70));

        jLabel14.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel14.setText("Status");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, -1));

        status.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        status.setText("<value>");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 340, -1));

        btnBack1.setBackground(new java.awt.Color(0, 105, 137));
        btnBack1.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 50));

        acceptOrder.setBackground(new java.awt.Color(0, 105, 137));
        acceptOrder.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        acceptOrder.setForeground(new java.awt.Color(255, 255, 255));
        acceptOrder.setText("Accept Appointment");
        acceptOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptOrderActionPerformed(evt);
            }
        });
        jPanel1.add(acceptOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 210, 60));

        assignDeliveryPerson.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        assignDeliveryPerson.setForeground(new java.awt.Color(255, 153, 51));
        assignDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDeliveryPersonActionPerformed(evt);
            }
        });
        jPanel1.add(assignDeliveryPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 210, -1));

        jButtonAddDeliveryMan.setBackground(new java.awt.Color(0, 105, 137));
        jButtonAddDeliveryMan.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jButtonAddDeliveryMan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddDeliveryMan.setText("Assign");
        jButtonAddDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDeliveryManActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 208, 120, 40));

        assignDeliveryPersonLabel.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        assignDeliveryPersonLabel.setText("Assign Doctor");
        jPanel1.add(assignDeliveryPersonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 160, 30));

        declineOrder.setBackground(new java.awt.Color(0, 105, 137));
        declineOrder.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        declineOrder.setForeground(new java.awt.Color(255, 255, 255));
        declineOrder.setText("Decline Appointment");
        declineOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                declineOrderMousePressed(evt);
            }
        });
        declineOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineOrderActionPerformed(evt);
            }
        });
        jPanel1.add(declineOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        ManageAppointments viewOrderDetails = new ManageAppointments(userProcessContainer, business, userAccount);
        userProcessContainer.add("ViewOrderDetails", viewOrderDetails);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void acceptOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptOrderActionPerformed

        if (labTestWorkRequest.getStatus().equals("Request to Hospital")) {
            labTestWorkRequest.setStatus("Waiting for doctor to be assigned");
            JOptionPane.showMessageDialog(null, " Appointment Scheduled. Waiting for doctor to be assigned");
        } else if (labTestWorkRequest.getStatus().equals("Waiting for doctor to be assigned")) {
            labTestWorkRequest.setStatus("Doctor Assigned");
            if (labTestWorkRequest.getDeliverMan() == null) {
                JOptionPane.showMessageDialog(null, " Doctor Assigned");
            } else {
                JOptionPane.showMessageDialog(null, "Doctor will be assigned");
            }
        } else {
            acceptOrder.setVisible(false);
        }
        change();
        status.setText(labTestWorkRequest.getStatus());
    }//GEN-LAST:event_acceptOrderActionPerformed

    private void assignDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDeliveryPersonActionPerformed
        index = assignDeliveryPerson.getSelectedIndex();
    }//GEN-LAST:event_assignDeliveryPersonActionPerformed

    private void jButtonAddDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDeliveryManActionPerformed
        if (index >= 0) {
            Doctor doctor = doctorDirectory.getDoctorList().get(assignDeliveryPerson.getSelectedIndex());
            labTestWorkRequest.setDoctor(doctor);
            JOptionPane.showMessageDialog(null, doctor + " Doctor assigned");
            fillDelUI();
        }
    }//GEN-LAST:event_jButtonAddDeliveryManActionPerformed

    private void declineOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declineOrderMousePressed
        declineOrder();
    }//GEN-LAST:event_declineOrderMousePressed

    private void declineOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_declineOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptOrder;
    private javax.swing.JComboBox<String> assignDeliveryPerson;
    private javax.swing.JLabel assignDeliveryPersonLabel;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton declineOrder;
    private javax.swing.JButton jButtonAddDeliveryMan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
