/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HospitalAdmin;

import Business.Business;
import Business.Hospital.HospitalAdmin;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dalea
 */
public class UpdateHospitalInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateHospitalInfoPanel
     */
    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;
    HospitalAdmin hospitalAdmin;
     public UpdateHospitalInfoPanel(JPanel userProcessContainer, Business business, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount = userAccount;
        hospitalAdmin = (HospitalAdmin)userAccount;
        initComponents();
        display(hospitalAdmin);
        btnsave.setVisible(false);
    }
      private void display(HospitalAdmin hospitalAdmin) {
        setVisibleEditable(false);
        txtname.setText(hospitalAdmin.getHospitalName()); 
        txtaddr.setText(hospitalAdmin.getAddress()); 
        txtcontact.setText(hospitalAdmin.getContactNumber()); 
    }
     
     private void setVisibleEditable(boolean value) {
        txtname.setEditable(value);        
        txtname.setEnabled(value);
        txtaddr.setEditable(value);        
        txtaddr.setEnabled(value);
        txtaddr.setEditable(value);        
        txtaddr.setEnabled(value);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hospName = new javax.swing.JLabel();
        lblAddr = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        txtaddr = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(163, 186, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospName.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        hospName.setText("Hospital Name");
        jPanel1.add(hospName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        lblAddr.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lblAddr.setText("Hospital Address");
        jPanel1.add(lblAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        lblContact.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lblContact.setText("Hospital Contact");
        jPanel1.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MANAGE HOSPITAL INFORMATION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 841, -1));

        btnupdate.setBackground(new java.awt.Color(0, 105, 137));
        btnupdate.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 109, 40));

        btnback.setBackground(new java.awt.Color(0, 105, 137));
        btnback.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 97, 44));

        btnsave.setBackground(new java.awt.Color(0, 105, 137));
        btnsave.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 103, 40));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 222, -1));
        jPanel1.add(txtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 222, -1));
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 222, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/HospitalAdmin/hospimg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 699, 361));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        btnupdate.setVisible(true);
        setVisibleEditable(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        HospitalAdminArea adminWorkAreaJPanel = new HospitalAdminArea(userProcessContainer,userAccount, business);
        userProcessContainer.add("AdminWorkAreaJPanel", adminWorkAreaJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        hospitalAdmin.setHospitalName(txtname.getText());
        setVisibleEditable(false);
    }//GEN-LAST:event_btnsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel hospName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddr;
    private javax.swing.JLabel lblContact;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
