/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.InsuranceAdminRole;

import Business.Business;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author dalea
 */
public class InsuranceAdmin extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAdmin
     */
    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;
    public InsuranceAdmin(JPanel userProcessContainer, UserAccount userAccount, Business business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.business=business;
        this.userAccount = userAccount; 
    }
    
    // Manage orders
    private void manageClaims() {
        ViewOrderDetails viewOrderDetails = new ViewOrderDetails(userProcessContainer,business,userAccount);
        userProcessContainer.add("ViewOrderDetails",viewOrderDetails);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
    
    private void manageInfo() {
        PatientRecords updatePatientInfoJPanel = new PatientRecords(userProcessContainer,business, userAccount);
        userProcessContainer.add("updatePatientInfoJPanel",updatePatientInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageApprovals = new javax.swing.JButton();
        btnViewPatientRecords = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(163, 186, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malayalam Sangam MN", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME INSURANCE ADMIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        btnManageApprovals.setBackground(new java.awt.Color(0, 105, 137));
        btnManageApprovals.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnManageApprovals.setForeground(new java.awt.Color(255, 255, 255));
        btnManageApprovals.setText("Manage approvals");
        btnManageApprovals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageApprovalsActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageApprovals, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, 210, 70));

        btnViewPatientRecords.setBackground(new java.awt.Color(0, 105, 137));
        btnViewPatientRecords.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnViewPatientRecords.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPatientRecords.setText("View Patient Records");
        btnViewPatientRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPatientRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 210, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/InsuranceAdminRole/insurance finance.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 850, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageApprovalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageApprovalsActionPerformed
        // TODO add your handling code here:
        manageClaims();
    }//GEN-LAST:event_btnManageApprovalsActionPerformed

    private void btnViewPatientRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientRecordsActionPerformed
        // TODO add your handling code here:
        manageInfo();
    }//GEN-LAST:event_btnViewPatientRecordsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageApprovals;
    private javax.swing.JButton btnViewPatientRecords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
